#!/bin/sh
__dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tmux new-session -d
tmux split-window -h ${__dir}/'ai_lab/core/start_notebook'
tmux split-window -v ${__dir}/'/ai_lab/core/start_tensorboard'
tmux -2 attach-session -d
